#!/bin/bash
#
# Copyright (c) 2018 BAE Systems
# Author: Christopher Clark

EXCESS_ARGS=()
while [[ $# -gt 0 ]] ; do
    case "$1" in
        --target-arch)      TARGET_ARCH="$2";      shift 2;;
        --ocaml-stdlib-dir) OCAML_STDLIB_DIR="$2"; shift 2;;
        -o)                 OUTPUT_FILE="$2";      shift 2;;

        *) EXCESS_ARGS+=("$1") ; shift ;;
    esac
done
set -- "${EXCESS_ARGS[@]}"

if [ $# != 0 ] ; then
    echo "Excess arguments were supplied : $@">&2
    exit 1
fi
if [ -z "${TARGET_ARCH}" ] ; then
    echo "--target-arch required parameter is missing.">&2
    exit 1
fi
if [ -z "${OCAML_STDLIB_DIR}" ] ; then
    echo "--ocaml-stdlib-dir required parameter is missing.">&2
    exit 1
fi
if [ -e "${OUTPUT_FILE}" ] ; then
    echo "Output file already exists; aborting. : ${OUTPUT_FILE}">&2
    exit 1
fi
[ -z "${OUTPUT_FILE}" ] || exec 1>"${OUTPUT_FILE}"

#---
# One variable is dependent on the OE build environment: OCAML_STDLIB_DIR
cat <<EOF
#define OCAML_STDLIB_DIR "${OCAML_STDLIB_DIR}"
EOF

case $TARGET_ARCH in
x86-64)
cat <<EOF
#define HAS_SECURE_GETENV
#define HAS_DUP3
#define HAS_PIPE2
#define HAS_ACCEPT4
EOF
;;
esac

# Common to both x86_64 and x86
# FIXME: verify settings on ARM
cat <<EOF
#define OCAML_OS_TYPE "Unix"
#define POSIX_SIGNALS
#define HAS_C99_FLOAT_OPS
#define HAS_GETRUSAGE
#define HAS_TIMES
#define HAS_SOCKETS
#define HAS_SOCKLEN_T
#define HAS_INET_ATON
#define HAS_IPV6
#define HAS_STDINT_H
#define HAS_UNISTD
#define HAS_OFF_T
#define HAS_DIRENT
#define HAS_REWINDDIR
#define HAS_LOCKF
#define HAS_MKFIFO
#define HAS_GETCWD
#define HAS_GETWD
#define HAS_GETPRIORITY
#define HAS_UTIME
#define HAS_UTIMES
#define HAS_DUP2
#define HAS_FCHMOD
#define HAS_TRUNCATE
#define HAS_SYS_SELECT_H
#define HAS_SELECT
#define HAS_NANOSLEEP
#define HAS_SYMLINK
#define HAS_WAITPID
#define HAS_WAIT4
#define HAS_GETGROUPS
#define HAS_SETGROUPS
#define HAS_INITGROUPS
#define HAS_TERMIOS
#define HAS_ASYNC_IO
#define HAS_SETITIMER
#define HAS_GETHOSTNAME
#define HAS_UNAME
#define HAS_GETTIMEOFDAY
#define HAS_MKTIME
#define HAS_SETSID
#define HAS_PUTENV
#define HAS_LOCALE
#define SUPPORT_DYNAMIC_LINKING
#define HAS_MMAP
#define HAS_PWRITE
#define HAS_NANOSECOND_STAT 1
#define HAS_GETHOSTBYNAME_R 6
#define HAS_GETHOSTBYADDR_R 8
#define HAS_MKSTEMP
#define HAS_NICE
#define HAS_STACK_OVERFLOW_DETECTION
#define HAS_SIGWAIT
#define HAS_HUGE_PAGES
#define HUGE_PAGE_SIZE (4 * 1024 * 1024)
EOF
